### ISSUE TITLE
Display errors in certain values/prices

### ISSUE THREAD

**Issue by cryptobanjo** [tellor-io/tellorPriceView#13]
Looks like we have some issues with some how the feed is displaying some of the values.

**Comment by skuhlmann** [comment]
Can you provide more detail? @cryptobanjo

**Comment by skuhlmann** [comment]
I saw some NAN values come through at times and refactored the original code a little to fix.
https://github.com/tellor-io/tellorPriceView/tree/feature/mode-switch
